runtime: go
api_version: go1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css 
  static_dir: css

- url: /imgs
  static_dir: imgs

- url: /js
  static_dir: js

- url: /engine/.*
  script: _go_app

- url: /sitemap.txt
  static_files: sitemap.txt
  upload: sitemap.txt

- url: /simploBuy.html
  static_files: simploBuy.html
  upload: simploBuy.html

- url: /amp-.*
  static_files: amp-index.html
  upload: amp-index.html

- url: /.*
  static_files: index.html
  upload: index.html